Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,42 +1,48 @@
 # This is a basic workflow to help you get started with Actions
 
-name: Docker Image CI  # workflow名称，可以随意改
+name: Deploy to Amazon ECS（Setp check）  # workflow名称，可以随意改
 
 # Controls when the workflow will run
-on: # workflow的事件钩子，告知程序说明时候出发自动部署
+on:                                      # workflow的事件钩子，告知程序说明时候出发自动部署
   # Triggers the workflow on push or pull request events but only for the master branch
   push:
-    branches: [ master ] # 在master分支有push操作的时候自动部署
+    branches: [ master ]                 # 在master分支有push操作的时候自动部署
   pull_request:
     branches: [ master ]
-
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  test: # make sure the action works on a clean machine without building
+  deploy:
+    name: Deploy
     runs-on: ubuntu-latest
+
     steps:
-    - uses: actions/checkout@v2
-    - name: Run the action # You would run your tests before this using the output to set state/desc
-      uses: Sibz/github-status-action@v1
-      with: 
-        authToken: ${{secrets.GITHUB_TOKEN}}
-        context: 'Test run'
-        description: 'Passed'
-        state: 'success'
-        sha: ${{github.event.pull_request.head.sha || github.sha}}
-  # This workflow contains a single job called "build"
+    - name: Check commit status
+      id: commit-status
+      run: |
+        # Check the status of the Git commit
+        CURRENT_STATUS=$(curl --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state');
+        echo "Current status is: $CURRENT_STATUS"
+        while [ "${CURRENT_STATUS^^}" = "PENDING" ]; 
+          do sleep 10; 
+          CURRENT_STATUS=$(curl --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state');
+        done;
+        echo "Current status is: $CURRENT_STATUS"
+        if [ "${CURRENT_STATUS^^}" = "FAILURE" ]; 
+          then echo "Commit status failed. Canceling execution"; 
+          exit 1; 
+        fi
   build: # 打包并上传docker镜像
-    #needs: [check]
+    needs: [deploy]
     runs-on: ubuntu-latest # 依赖的环境      
     steps:
       - uses: actions/checkout@v2
       - name: Build Image
       # ${{ secrets.DOCKER_REPOSITORY }}是读取之前在Secret创建的名为DOCKER_REPOSITORY的值
-        run: docker build -t ${{ secrets.DOCKER_REPOSITORY }}:1.0 ./ # 打包并docker镜像，版本为latest
+        run: docker build -t ${{ secrets.DOCKER_REPOSITORY }}:latest ./ # 打包并docker镜像，版本为latest
       - name: Login to Registry # 登录阿里云镜像服务器
         run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
       - name: Push Image # 推送镜像，设置版本为latest
-        run: docker push ${{ secrets.DOCKER_REPOSITORY }}:1.0
+        run: docker push ${{ secrets.DOCKER_REPOSITORY }}:latest
